
# # Generated by Selenium IDE
from django.test import TestCase


import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select

class TestGraficaDonut():
    def setUp(self):
        self.driver = webdriver.Chrome()
        
    def test_graficaDonut(self):
        self.driver.get("https://picaro-decide.herokuapp.com/admin/login/?next=/admin/")
        self.driver.find_element_by_id('id_username').send_keys("admin")
        self.driver.find_element_by_id('id_password').send_keys("picarodecide")
        self.driver.find_element_by_id('login-form').click()
        self.driver.get("https://picaro-decide.herokuapp.com/visualizer/5/")
        #Aquí se comprueba que se encuentra la gráfica circular
        assert self.driver.find_element(By.CSS_SELECTOR, "section > #table th:nth-child(1) > .heading").text == "Gráfico Circular"
        elements = self.driver.find_elements(By.ID, "myChart")
        assert len(elements) > 0

    def tearDown(self):
        self.driver.quit()


class TestTablaResultados():
    def setUp(self):
        self.driver = webdriver.Chrome()
        
    def test_graficaDonut(self):
        self.driver.get("https://picaro-decide.herokuapp.com/admin/login/?next=/admin/")
        self.driver.find_element_by_id('id_username').send_keys("admin")
        self.driver.find_element_by_id('id_password').send_keys("picarodecide")
        self.driver.find_element_by_id('login-form').click()
        self.driver.get("https://picaro-decide.herokuapp.com/visualizer/5/")
        assert self.driver.find_element(By.CLASS_NAME, "theTable")
        assert self.driver.find_element(By.ID, "exportarTab")
        #Aquí se comprueba que aparecen los resultados de la votación (se comprueba que aparecen 2 opciones de la votación
        #se supone que una votación tiene al menos 2 opciones)
        opcion1 = self.driver.find_elements(By.CSS_SELECTOR, "tbody > tr:nth-child(1) > th")
        assert len(opcion1) > 0
        opcion2 = self.driver.find_elements(By.CSS_SELECTOR, "tbody > tr:nth-child(1) > th")
        assert len(opcion2) > 0
        

    def tearDown(self):
        self.driver.quit()


class TestBotonReturn():
    def setUp(self):
        self.driver = webdriver.Chrome()
        
    def test_graficaDonut(self):
        #Aqui se comprueba que si le das al botón return vuelve a la página anterior
        self.driver.get("https://picaro-decide.herokuapp.com/admin/login/?next=/admin/")
        self.driver.find_element_by_id('id_username').send_keys("admin")
        self.driver.find_element_by_id('id_password').send_keys("picarodecide")
        self.driver.find_element_by_id('login-form').click()
        self.driver.get("https://picaro-decide.herokuapp.com/visualizer/contactUs")
        assert self.driver.current_url == "https://picaro-decide.herokuapp.com/visualizer/contactUs/"
        self.driver.get("https://picaro-decide.herokuapp.com/visualizer/5/")
        assert self.driver.current_url == "https://picaro-decide.herokuapp.com/visualizer/5/"
        self.driver.find_element(By.CSS_SELECTOR, "#app-visualizer > .btn").click()
        assert self.driver.current_url == "https://picaro-decide.herokuapp.com/visualizer/contactUs/"
        

    def tearDown(self):
        self.driver.quit()

# if __name__ == '__main__':
#     unittest.main()

