# Generated by Django 2.0 on 2021-01-07 15:14

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_options',
            field=models.PositiveIntegerField(choices=[(1, 'Simple question'), (2, 'Preference question')], default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='yes_no_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='pref_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, validators=[voting.models.no_past]),
        ),
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.AddField(
            model_name='voting',
            name='question',
            field=models.ManyToManyField(related_name='voting', to='voting.Question'),
        ),
    ]
