# Generated by Django 2.0 on 2021-01-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
