# Generated by Django 2.0 on 2021-01-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20201230_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.PositiveIntegerField(choices=[(1, 'Unique Answer'), (2, 'Preference answer')], default='1', verbose_name='Answer type'),
        ),
    ]
