# Generated by Django 2.0 on 2021-01-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20210102_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoption',
            old_name='preference',
            new_name='rank_order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_type',
        ),
        migrations.AddField(
            model_name='question',
            name='option_types',
            field=models.PositiveIntegerField(choices=[(1, 'Unique option'), (2, 'Multiple option'), (3, 'Rank order scale')], default='1'),
        ),
        migrations.AddField(
            model_name='voting',
            name='started_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
