# Generated by Django 2.0 on 2021-01-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20210117_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
