# Generated by Django 2.0 on 2021-01-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20210103_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('option', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_types',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='rank_order',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='started_by',
        ),
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voting',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='questionorder',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_options', to='voting.Question'),
        ),
    ]
