# Generated by Django 2.0 on 2021-01-03 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20210103_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionMultiple',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_opcion', models.CharField(max_length=100)),
                ('n_votado', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_opcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('textoPregunta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaMultiple',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('textoPregunta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaPreferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('textoPregunta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaBinaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.BooleanField(choices=[(1, 'Sí'), (0, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPreferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orden_preferencia', models.PositiveIntegerField(blank=True, null=True)),
                ('opcionRespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.OpcionRespuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VotacionBinaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VotacionMultiple',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VotacionPreferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='questionorder',
            name='question',
        ),
        migrations.DeleteModel(
            name='QuestionOrder',
        ),
        migrations.AddField(
            model_name='respuestabinaria',
            name='votacionBinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.VotacionBinaria'),
        ),
        migrations.AddField(
            model_name='preguntapreferencia',
            name='votacionPreferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.VotacionPreferencia'),
        ),
        migrations.AddField(
            model_name='preguntamultiple',
            name='votacionMultiple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.VotacionMultiple'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='votacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Votacion'),
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='preguntaPreferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.PreguntaPreferencia'),
        ),
        migrations.AddField(
            model_name='opcionmultiple',
            name='preguntaMultiple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.PreguntaMultiple'),
        ),
    ]
