# Generated by Django 2.0 on 2021-01-03 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20210103_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOptionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.PositiveIntegerField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('option', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='opcionmultiple',
            name='preguntaMultiple',
        ),
        migrations.RemoveField(
            model_name='opcionrespuesta',
            name='preguntaPreferencia',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='votacion',
        ),
        migrations.RemoveField(
            model_name='preguntamultiple',
            name='votacionMultiple',
        ),
        migrations.RemoveField(
            model_name='preguntapreferencia',
            name='votacionPreferencia',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuestabinaria',
            name='votacionBinaria',
        ),
        migrations.RemoveField(
            model_name='respuestapreferencia',
            name='opcionRespuesta',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.PositiveIntegerField(choices=[(1, 'Unique Answer'), (2, 'Preference answer')], default='1', verbose_name='Answer type'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='OpcionMultiple',
        ),
        migrations.DeleteModel(
            name='OpcionRespuesta',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='PreguntaMultiple',
        ),
        migrations.DeleteModel(
            name='PreguntaPreferencia',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.DeleteModel(
            name='RespuestaBinaria',
        ),
        migrations.DeleteModel(
            name='RespuestaPreferencia',
        ),
        migrations.DeleteModel(
            name='Votacion',
        ),
        migrations.DeleteModel(
            name='VotacionBinaria',
        ),
        migrations.DeleteModel(
            name='VotacionMultiple',
        ),
        migrations.DeleteModel(
            name='VotacionPreferencia',
        ),
        migrations.AddField(
            model_name='questionoptionorder',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_options', to='voting.Question'),
        ),
    ]
