# Generated by Django 2.0 on 2021-01-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20210103_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.AlterField(
            model_name='questionoptionorder',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.Question'),
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
