# Generated by Django 2.0 on 2021-01-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20210104_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_number', models.PositiveIntegerField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('option', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='questionoptionorder',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_type',
        ),
        migrations.AddField(
            model_name='question',
            name='question_options',
            field=models.PositiveIntegerField(choices=[(1, 'Simple question'), (2, 'Preference question')], default=1),
        ),
        migrations.DeleteModel(
            name='QuestionOptionOrder',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.Question'),
        ),
    ]
